"""Identifiers and metadata shared by paper portfolio orchestration."""

MOMENTUM_LIVE = "MOMENTUM_LIVE"
REVERSAL_LIVE = "REVERSAL_LIVE"
ETF_TOP2_CANDIDATE = "ETF_TOP2_CANDIDATE"
DEFENSIVE_CANDIDATE = "DEFENSIVE_CANDIDATE"
SPY_BUY_HOLD = "SPY_BUY_HOLD"
BALANCED_60_40 = "BALANCED_60_40"
SHY_BUY_HOLD = "SHY_BUY_HOLD"

STOCK_PORTFOLIOS = (MOMENTUM_LIVE, REVERSAL_LIVE)
FORWARD_ETF_PORTFOLIOS = (
    ETF_TOP2_CANDIDATE,
    DEFENSIVE_CANDIDATE,
    SPY_BUY_HOLD,
    BALANCED_60_40,
    SHY_BUY_HOLD,
)
ALL_PAPER_PORTFOLIOS = STOCK_PORTFOLIOS + FORWARD_ETF_PORTFOLIOS
